name: Build and Deploy
on:
  push:
    branches:
      - "HexoBlog"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@latest
        with:
          persist-credentials: false

      - name: Setup Node.js 16.x
        uses: actions/setup-node@latest
        with:
          node-version: '16.x'

      - name: Install Dependencies and Build 🔧
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          folder: "public"