name: Build and Deploy
on: push # 当仓库被推送时触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行在最新版本的ubuntu虚拟环境上
    steps:
      - name: Checkout 🛎️ # 步骤1：检出代码
        uses: actions/checkout@v2 # 使用官方的checkout动作
        with:
          persist-credentials: false # 如果使用actions/checkout@v2，大多数情况下需要将persist-credentials设置为false，以便部署能够正常工作

      - name: Install and Build 🔧 # 步骤2：安装并构建项目。这个示例项目使用npm构建，并将结果输出到“build”文件夹。根据你的项目需要更改这些命令，或者如果你的站点是预先构建的，则完全删除此步骤。
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Deploy 🚀 # 步骤3：部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3 # 使用第三方的github-pages-deploy-action动作
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token进行身份验证
          BRANCH: main # 部署到的分支
          FOLDER: public # 部署的文件夹